#!/usr/bin/env bash
# bench-record.sh — run the code bench and write a machine-stamped, committable
# record to bench-results/.
#
# Why this exists: bench-out/ is gitignored (raw model responses and generated
# sources — reproducible noise), so benchmark RESULTS were never saved anywhere.
# That is fine on one machine and useless the moment you want to compare an
# M1 Max against an M4 or M5.
#
# A cross-machine comparison is only meaningful if the things that are NOT the
# CPU are pinned, so the record captures all of them:
#
#   model digest    `ollama list` IDs. Tags get re-uploaded; two machines on
#                   "gemma4:26b" can hold different weights. The digest is the
#                   only honest identity.
#   toolchain       javac / kotlinc / swiftc versions. This bench grades by
#                   COMPILING the output, so a different Swift release can flip
#                   a PASS to a FAIL with the model held constant. Without this
#                   you would blame the chip.
#   ollama version  inference engine changes move tok/s on their own.
#   RAM             decides whether a model runs on GPU or spills.
#
# Usage:
#   ./bench-record.sh                      re-record from the existing bench-out log
#   ./bench-record.sh <model> [model...]   run the bench for these models, then record
#
# Output: bench-results/<chip-slug>.md  (one file per machine, diffable)

set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/bench-results"
mkdir -p "$OUT"

LOG="$HERE/bench-out/headtohead.log"

if [[ $# -gt 0 ]]; then
    command -v ollama >/dev/null || { echo "ollama not found"; exit 1; }
    curl -sf --max-time 5 http://localhost:11434/api/version >/dev/null \
        || { echo "ollama daemon unreachable — open Ollama.app or run: ollama serve"; exit 1; }
    : > "$LOG"
    for m in "$@"; do
        "$HERE/ollama-code-bench-one.sh" "$m" 2>&1 | tee -a "$LOG"
    done
fi

[[ -s "$LOG" ]] || { echo "no bench log at $LOG — pass model tags to run the bench first"; exit 1; }

# --- provenance -------------------------------------------------------------
chip=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo unknown)
ram=$(( $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1024 / 1024 / 1024 ))
cores=$(sysctl -n hw.ncpu 2>/dev/null || echo '?')
osver=$(sw_vers -productVersion 2>/dev/null || echo '?')
osbuild=$(uname -r)
oll=$(ollama --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
jv=$(javac -version 2>&1 | head -1)
kv=$(kotlinc -version 2>&1 | head -1 | sed 's/^info: //')
sv=$(swiftc --version 2>/dev/null | head -1)

# `sed -E` deliberately: BSD sed (macOS) does not honour \+ in a basic regex,
# so the plain-BRE version silently left spaces in and produced "m1 max-64gb.md".
slug=$(printf '%s' "$chip" | tr '[:upper:]' '[:lower:]' | sed -E 's/^apple //; s/[^a-z0-9]+/-/g; s/-$//')
dest="$OUT/${slug}-${ram}gb.md"

{
printf '# Bench record — %s, %s GB\n\n' "$chip" "$ram"
printf 'Generated by `bench-record.sh`. One file per machine; compare by diffing.\n\n'
printf '| field | value |\n|---|---|\n'
printf '| chip | %s |\n' "$chip"
printf '| cores | %s |\n' "$cores"
printf '| RAM | %s GB |\n' "$ram"
printf '| macOS | %s (Darwin %s) |\n' "$osver" "$osbuild"
printf '| ollama | %s |\n' "${oll:-?}"
printf '| javac | %s |\n' "$jv"
printf '| kotlinc | %s |\n' "$kv"
printf '| swiftc | %s |\n' "$sv"
printf '| recorded | %s |\n' "$(date +%Y-%m-%d)"
printf '\n## Results\n\n'
printf 'Three one-shot tasks (Java 21 sealed/pattern-match, Kotlin coroutines,\n'
printf 'Swift 6 actor+Codable). Graded by compiling AND running the output, so a\n'
printf 'PASS means it actually ran, not that it looked plausible.\n\n'
printf '**This bench is one-shot generation only** — no tool calls, no iteration.\n'
printf 'It does not measure agentic ability; a model can top this table and still\n'
printf 'be the wrong choice for an OpenCode/Pi driver.\n\n'
printf '| model | digest | size | score | java | kotlin | swift | mean tok/s |\n'
printf '|---|---|---|---|---|---|---|---|\n'
} > "$dest"

python3 - "$LOG" >> "$dest" <<'PY'
import re, subprocess, sys
log = open(sys.argv[1], errors="replace").read()

meta = {}
for line in subprocess.run(["ollama","list"],capture_output=True,text=True).stdout.splitlines()[1:]:
    p = line.split()
    if len(p) >= 3:
        meta[p[0]] = (p[1], " ".join(p[2:4]))

rows, cur = {}, None
for line in log.splitlines():
    m = re.match(r"#+\s*(\S+)\s*#+", line.strip())
    if m:
        cur = m.group(1); rows.setdefault(cur, {}); continue
    m = re.match(r"\[(\w+)\s*\]\s*gen\s+([\d.]+)s\s*\|\s*(\d+) tok @ ([\d.]+) tok/s \| (.*)", line.strip())
    if m and cur:
        t, gen, _tok, tps, verdict = m.groups()
        rows[cur][t] = (verdict.startswith("COMPILE ok | RUN ok"), float(gen), float(tps))

TASKS = ["java","kotlin","swift"]
out = []
for mdl, t in rows.items():
    score = sum(1 for k in TASKS if t.get(k,(False,))[0])
    cells, tpss = [], []
    for k in TASKS:
        if k not in t: cells.append("–"); continue
        ok, gen, tps = t[k]
        cells.append(f"{'✅' if ok else '❌'} {gen:.1f}s")
        tpss.append(tps)
    mean = sum(tpss)/len(tpss) if tpss else 0
    d, sz = meta.get(mdl, ("?","?"))
    out.append((score, mean, mdl, d, sz, cells))

for score, mean, mdl, d, sz, cells in sorted(out, key=lambda r:(-r[0],-r[1])):
    print(f"| `{mdl}` | `{d}` | {sz} | **{score}/3** | {cells[0]} | {cells[1]} | {cells[2]} | {mean:.1f} |")
PY

echo "wrote $dest"
