#!/bin/sh
# rm -f everywhere: quiet on a fresh machine (no "No such file" spam) and
# guarantees the following ln -s can't silently no-op against a leftover file.
rm -f ~/.zshrc
rm -f ~/.zshenv
rm -f ~/.gitconfig
rm -f ~/.gitignore
rm -f ~/.jshintrc
rm -f ~/.inputrc
rm -f ~/.tigrc
rm -f ~/.ssh/config
rm -f ~/.dircolors
rm -f ~/.mackup.cfg
rm -f ~/.tmux.conf
rm -f ~/.vimrc
rm -f ~/.p10k.zsh

ln -s ~/projects/dotfiles/.zshrc ~/.zshrc
ln -s ~/projects/dotfiles/.zshenv ~/.zshenv
ln -s ~/projects/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/projects/dotfiles/.gitignore ~/.gitignore
ln -s ~/projects/dotfiles/.jshintrc ~/.jshintrc
ln -s ~/projects/dotfiles/.inputrc ~/.inputrc
ln -s ~/projects/dotfiles/.tigrc ~/.tigrc
ln -s ~/projects/dotfiles/.vimrc ~/.vimrc
ln -s ~/projects/dotfiles/.ssh/config ~/.ssh/config
ln -s ~/projects/dotfiles/.dircolors ~/.dircolors
ln -s ~/projects/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/projects/dotfiles/.p10k.zsh ~/.p10k.zsh

# Ghostty terminal config
# On macOS, Ghostty loads ~/Library/Application Support/com.mitchellh.ghostty/config
# AFTER the XDG path, so the macOS-native one wins on conflicts. Put the symlink there
# and drop the XDG one to avoid split-brain config.
GHOSTTY_MACOS_DIR="$HOME/Library/Application Support/com.mitchellh.ghostty"
mkdir -p "$GHOSTTY_MACOS_DIR"
rm -f "$GHOSTTY_MACOS_DIR/config"
ln -s ~/projects/dotfiles/ghostty/config "$GHOSTTY_MACOS_DIR/config"
rm -rf ~/.config/ghostty

# cmux terminal config
mkdir -p ~/.config/cmux
rm -f ~/.config/cmux/settings.json
ln -s ~/projects/dotfiles/cmux/settings.json ~/.config/cmux/settings.json

# herdr — terminal workspace manager for AI agents (tmux-alike)
mkdir -p ~/.config/herdr
rm -f ~/.config/herdr/config.toml
ln -s ~/projects/dotfiles/herdr/config.toml ~/.config/herdr/config.toml

# herdr notification plugin. Lives in its own repo now — gAmUssA/herdr-notify,
# published to the herdr marketplace — so it is INSTALLED by id rather than
# linked at a path here. Not a symlink either way: herdr keeps its own plugin
# registry and fetches the source itself.
#
# It owns desktop banners for agents running inside herdr; claude/stop-hook.sh
# checks that gamussa.notify is enabled before staying quiet, so if this step is
# skipped the hook notifies from itself instead of going silent.
#
# For plugin development, clone the repo and `herdr plugin link <checkout>`,
# which replaces the installed copy until you unlink it.
if command -v herdr >/dev/null 2>&1; then
  herdr plugin install gAmUssA/herdr-notify --yes >/dev/null 2>&1 \
    && echo "herdr plugin -> gamussa.notify installed" \
    || echo "skip: herdr plugin install (already installed, or server not running)"
fi

# Agent integrations — herdr (pane/agent state) and moshi-hook (Moshi iOS app).
# Each agent's hook config is GENERATED by these installers with absolute paths
# (~/.copilot/settings.json, ~/.gemini/settings.json, opencode/pi plugin dirs…),
# so the repo does not track those files; it re-runs the installers, which are
# idempotent. Only agents whose CLI is present are touched.
#
# Must run BEFORE the Claude block below, and against a throwaway copy of
# Claude's settings: moshi-hook replaces ~/.claude/settings.json, and herdr
# edits it THROUGH the symlink — it does not recognize the tracked
# "$HOME/.claude/hooks/herdr-agent-state.sh" hook as its own, so it appends a
# second one with a hardcoded /Users/<name> path straight into this public
# repo. Claude's hooks for both are already tracked; the relink below replaces
# the copy. (A drifted regular file is left as is — reconcile-check.sh first.)
mkdir -p ~/.claude
if [ -L ~/.claude/settings.json ]; then
  rm ~/.claude/settings.json
  cp ~/projects/dotfiles/claude/settings.json ~/.claude/settings.json
fi
agent_ids=""
for pair in claude:claude codex:codex copilot:copilot opencode:opencode pi:pi grok:grok agy:antigravity-cli; do
  bin=${pair%%:*}; id=${pair#*:}
  command -v "$bin" >/dev/null 2>&1 || continue
  agent_ids="$agent_ids $bin"
  command -v herdr >/dev/null 2>&1 && herdr integration install "$id" >/dev/null 2>&1 \
    || echo "skip: herdr integration $id"
done
# Call moshi-hook by the path its brew service runs from, not the PATH symlink:
# the daemon judges hook files "current" by comparing them with what IT would
# write, binary path included. Hooks written via /opt/homebrew/bin/moshi-hook
# made the daemon — and so the Moshi app — report opencode, copilot and pi as
# "not set up" while `moshi-hook doctor` from a shell said all was fine.
moshi_bin="$(brew --prefix 2>/dev/null)/opt/moshi-hook/bin/moshi-hook"
if [ -x "$moshi_bin" ] && [ -n "$agent_ids" ]; then
  # moshi names antigravity "antigravity" (herdr: "antigravity-cli").
  targets=$(echo $agent_ids | sed 's/agy/antigravity/' | tr ' ' ',')
  "$moshi_bin" install --target "$targets" >/dev/null 2>&1 \
    && echo "moshi-hook -> hooks for $targets" || echo "skip: moshi-hook install"
fi

# sesh — tmux session manager config
mkdir -p ~/.config/sesh
rm -f ~/.config/sesh/sesh.toml
ln -s ~/projects/dotfiles/sesh/sesh.toml ~/.config/sesh/sesh.toml

# Claude Code config (settings + custom statusline + stop hook script)
# Skips settings.local.json — that's meant to stay per-machine.
mkdir -p ~/.claude
rm -f ~/.claude/settings.json ~/.claude/statusline.sh ~/.claude/stop-hook.sh ~/.claude/block-secrets.py ~/.claude/settings-link-guard.sh
ln -s ~/projects/dotfiles/claude/settings.json ~/.claude/settings.json
ln -s ~/projects/dotfiles/claude/statusline.sh ~/.claude/statusline.sh
ln -s ~/projects/dotfiles/claude/stop-hook.sh ~/.claude/stop-hook.sh
ln -s ~/projects/dotfiles/claude/block-secrets.py ~/.claude/block-secrets.py
ln -s ~/projects/dotfiles/claude/settings-link-guard.sh ~/.claude/settings-link-guard.sh

# Tools that write Claude's settings by replacing the file (Paseo,
# tmux-assistant-resurrect) turn the symlink above back into a plain file, after
# which the live config and this repo drift apart silently. settings-link-guard.sh
# runs as a SessionStart hook and says so.

# Git hooks for THIS repo. Not a symlink into .git/hooks — core.hooksPath points
# git at the version-tracked githooks/ directory instead, so the hooks travel
# with the repo and a new machine picks them up here.
#
# githooks/pre-commit matters because ~/.claude/settings.json is a symlink INTO
# this repo: Claude Code writes config changes straight into tracked content,
# and those writes don't pass through claude/block-secrets.py (that one guards
# the agent's tool calls, not Claude Code's own config writes). This repo is
# public, so the pre-commit scan is the backstop.
git -C ~/projects/dotfiles config core.hooksPath githooks

# 1Password secret references (op:// pointers, no secrets — safe to version).
# Consumed by zsh_custom/onepassword.zsh: `opsync` resolves these once into the
# login keychain so new shells cost zero biometric prompts; `opx` resolves them
# fresh per command. ~/.config/op also holds op's own config, so link the single
# file rather than the directory.
mkdir -p ~/.config/op && chmod 700 ~/.config/op   # op refuses to run if this is group/world-readable
rm -f ~/.config/op/agents.refs
ln -s ~/projects/dotfiles/op/agents.refs ~/.config/op/agents.refs

# 1Password SSH agent key list. No secrets — vault/item names only; the private
# keys stay in 1Password and are served over the agent socket that
# .ssh/config's `IdentityAgent` points at.
#
# This file existing means the agent offers ONLY the keys it lists, so a key
# added in the 1Password UI but not here is invisible to ssh. Versioning it is
# what stops a new Mac from re-hitting that.
mkdir -p ~/.config/1Password/ssh
rm -f ~/.config/1Password/ssh/agent.toml
ln -s ~/projects/dotfiles/op/ssh-agent.toml ~/.config/1Password/ssh/agent.toml

# The stable socket path .ssh/config points at. Enabling the agent does NOT
# create this on current 1Password (seen on Daystrom): the real socket lives
# only in the app group container, so link to it ourselves.
op_sock="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
if [ ! -e ~/.1password/agent.sock ]; then
  mkdir -p ~/.1password
  ln -sfn "$op_sock" ~/.1password/agent.sock
fi

# Local AI coding agents — Ollama provider configs only. Machine state
# (opencode node_modules/bun.lock, pi auth.json/sessions/settings.json) is
# deliberately NOT versioned, so symlink the single config file in each.
mkdir -p ~/.config/opencode ~/.pi/agent ~/.agents/skills
rm -f ~/.config/opencode/opencode.json ~/.pi/agent/models.json
ln -s ~/projects/dotfiles/opencode/opencode.json ~/.config/opencode/opencode.json
ln -s ~/projects/dotfiles/pi/models.json ~/.pi/agent/models.json
# Shared agent skill (SKILL.md open standard) in the universal ~/.agents/skills
# location — discovered by OpenCode, Pi, AND Claude Code alike. Pi has no MCP,
# so web search is a skill (CLI tool + SKILL.md) rather than an MCP server.
rm -rf ~/.agents/skills/tavily-search
ln -s ~/projects/dotfiles/agents/skills/tavily-search ~/.agents/skills/tavily-search

# micro editor — file-level symlinks (NOT the whole dir: micro keeps machine
# state in ~/.config/micro/backups and buffers alongside the config).
mkdir -p ~/.config/micro
rm -f ~/.config/micro/settings.json ~/.config/micro/bindings.json
ln -s ~/projects/dotfiles/micro/settings.json ~/.config/micro/settings.json
ln -s ~/projects/dotfiles/micro/bindings.json ~/.config/micro/bindings.json

# AeroSpace — tiling WM. A plain file it reads directly (not a cfprefsd plist),
# so a symlink is safe. ~/.aerospace.toml would take precedence over the XDG path,
# so make sure a stray one can't shadow the repo copy.
mkdir -p ~/.config/aerospace
rm -f ~/.config/aerospace/aerospace.toml ~/.aerospace.toml
ln -s ~/projects/dotfiles/aerospace/aerospace.toml ~/.config/aerospace/aerospace.toml

# Karabiner-Elements — whole-directory symlink (the approach Karabiner's sync
# docs support; file-level symlinks are risky because the GUI rewrites
# karabiner.json on every change). automatic_backups/ inside is gitignored.
# Restart the user server after linking so it picks up the new path.
if [ -d ~/.config/karabiner ] && [ ! -L ~/.config/karabiner ]; then
  mv ~/.config/karabiner ~/.config/karabiner.pre-symlink-backup
fi
rm -f ~/.config/karabiner
ln -s ~/projects/dotfiles/karabiner ~/.config/karabiner
launchctl kickstart -k "gui/$(id -u)/org.pqrs.service.agent.Karabiner-Console-User-Server" 2>/dev/null

# Hammerspoon — entry point + caffeine + ollama menubar modules.
# File-level symlinks so anything else in ~/.hammerspoon (Spoons/, scratch
# files, Hammerspoon's own state) is left alone.
mkdir -p ~/.hammerspoon
rm -f ~/.hammerspoon/init.lua ~/.hammerspoon/caffeine.lua ~/.hammerspoon/ollama.lua ~/.hammerspoon/claude_sessions.lua ~/.hammerspoon/aerospace_hud.lua
ln -s ~/projects/dotfiles/hammerspoon/init.lua ~/.hammerspoon/init.lua
ln -s ~/projects/dotfiles/hammerspoon/caffeine.lua ~/.hammerspoon/caffeine.lua
ln -s ~/projects/dotfiles/hammerspoon/ollama.lua ~/.hammerspoon/ollama.lua
ln -s ~/projects/dotfiles/hammerspoon/claude_sessions.lua ~/.hammerspoon/claude_sessions.lua
ln -s ~/projects/dotfiles/hammerspoon/aerospace_hud.lua ~/.hammerspoon/aerospace_hud.lua

ls -lah ~/.zshrc
ls -lah ~/.gitconfig
ls -lah ~/.gitignore
ls -lah ~/.jshintrc
ls -lah ~/.inputrc
ls -lah ~/.tigrc
ls -lah ~/.vimrc
ls -lah ~/.ssh/config
ls -lah ~/.dircolors
ls -lah ~/.tmux.conf
ls -lah ~/.p10k.zsh
ls -lah "$HOME/Library/Application Support/com.mitchellh.ghostty/config"
ls -lah ~/.config/cmux/settings.json
ls -lah ~/.claude/settings.json ~/.claude/statusline.sh ~/.claude/stop-hook.sh
ls -lah ~/.hammerspoon/init.lua ~/.hammerspoon/caffeine.lua ~/.hammerspoon/ollama.lua ~/.hammerspoon/claude_sessions.lua ~/.hammerspoon/aerospace_hud.lua
ls -lah ~/.config/opencode/opencode.json ~/.pi/agent/models.json ~/.agents/skills/tavily-search
ls -lah ~/.config/op/agents.refs
ls -lah ~/.config/1Password/ssh/agent.toml
echo "git hooks -> $(git -C ~/projects/dotfiles config core.hooksPath) ($(cd ~/projects/dotfiles/githooks && echo *))"

# thefuck — installed via pipx pinned to python@3.11 (the brew formula has a
# stale openssl@1.1 dep, and thefuck 3.32 imports `distutils` which Python
# 3.12+ removed). Idempotent: re-runs only if not already installed.
if command -v pipx >/dev/null 2>&1; then
  if ! pipx list 2>/dev/null | grep -q "package thefuck"; then
    if [ -x /opt/homebrew/bin/python3.11 ]; then
      pipx install --python /opt/homebrew/bin/python3.11 thefuck
    else
      echo "skip: thefuck install — install python@3.11 first (brew install python@3.11)"
    fi
  fi
fi
